services:
  database:
    container_name: database
    image: mysql:8.0
    env_file: ./.env.dev
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    ports:
      - '4306:3306'
    volumes:
      - ./mysql:/var/lib/mysql

  php:
    container_name: php
    build:
      context: ./php
      target: development
    environment:
      APP_ENV: dev
    ports:
      - 8080:80
      - 8443:443
    volumes:
      - ./apache/default.conf:/etc/apache2/sites-enabled/000-default.conf
      - ./apache/default-ssl.conf:/etc/apache2/sites-enabled/000-default-ssl.conf
      - ./etc/ssl:/etc/ssl
      - ./backend:/var/www
      - ./backend/public/covers:/var/www/public/covers:rw
    user: "${UID}:${GID}"
    depends_on:
      - database

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      target: development
    command: npm run dev -- --host
    ports:
      - 5173:5173
    volumes:
      - ./client/src:/app/src
      - /app/node_modules

  phpma:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    env_file: ./.env
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: "${DB_HOST}"
      PMA_USER: root
      PMA_PASSWORD: "${DB_ROOT_PASSWORD}"
      UPLOAD_LIMIT: 20M
    ports:
      - 8899:80
  mailhog:
    image: mailhog/mailhog
    logging:
      driver: 'none'
    ports:
      - 1025:1025 #SMTP
      - 8025:8025 #Boite mail