services:
  database:
    container_name: database
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: secretpassword
      MYSQL_DATABASE: libtrack
      MYSQL_USER: symfony
      MYSQL_PASSWORD: secretpassword
    ports:
      - '4306:3306'
    volumes:
      - ./mysql:/var/lib/mysql

  php:
    container_name: php
    build:
      context: ./php
    # environment:
    #   APP_ENV: dev
    ports:
      - 8080:80
      - 8443:443
    volumes:
      - ./apache/default.conf:/etc/apache2/sites-enabled/000-default.conf
      - ./apache/default-ssl.conf:/etc/apache2/sites-enabled/000-default-ssl.conf
      - ./etc/ssl:/etc/ssl
      - ./app:/var/www
    depends_on:
      - database

  client:
    build: ./client
    command: npm run dev -- --host
    restart: always
    environment:
      - VITE_API_URL=http://localhost:8080
    ports:
      - 5173:5173
    volumes:
      - ./client/src:/app/src
      - /app/node_modules

  phpma:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: database
      PMA_USER: root
      PMA_PASSWORD: secretpassword
      UPLOAD_LIMIT: 20M
    ports:
      - 8899:80
  mailhog:
    image: mailhog/mailhog
    logging:
      driver: 'none'
    ports:
      - 1025:1025 #SMTP
      - 8025:8025 #Boite mail