gesdinet_jwt_refresh_token:
  refresh_token_class: App\Entity\RefreshToken
  ttl: 2592000 # 30 days
  ttl_update: true # Update TTL at every refresh
  token_parameter_name: refresh_token
  user_provider: security.user.provider.concrete.app_user_provider
  single_use: true # Refresh tokens can be used only once
