vich_uploader:
  db_driver: orm

  metadata:
    type: attribute

  mappings:
    artist_images:
      uri_prefix: /images/artists
      upload_destination: "%kernel.project_dir%/public/images/artists"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

      inject_on_load: false
      delete_on_update: true
      delete_on_remove: true
